"""
Configure `pytest` library.

DO NOT EDIT: This module is automatically generated by the script
``mock_upgrade.py``. Edit file ``conftest_source.py`` instead and run
the aforementioned script.

.. note::
    This script uses beta feature `responses._add_from_file` (as of
    `responses` version 0.23.3).
"""

# SPDX-FileCopyrightText: 2023 Lauri Salmela <lauri.m.salmela@gmail.com>
#
# SPDX-License-Identifier: MIT

from pathlib import Path
from typing import Union

import pytest
import responses

from xbrl_filings_api import FilingSet, ResourceCollection

MOCK_URL_DIR_NAME = 'mock_responses'

mock_dir_path = Path(__file__).parent / MOCK_URL_DIR_NAME


def _get_path(set_id):
    """Get absolute file path of the mock URL collection file."""
    file_path = mock_dir_path / f'{set_id}.yaml'
    return str(file_path)


@pytest.fixture
def filings() -> FilingSet:
    """Return FilingSet."""
    return FilingSet()


@pytest.fixture
def res_colls(filings) -> dict[str, ResourceCollection]:
    """Return subresource collections for filings fixture."""
    return {
        'Entity': filings.entities,
        'ValidationMessage': filings.validation_messages
        }


@pytest.fixture(scope='module')
def mock_response_data():
    """Arbitrary data to mock download."""
    return '0123456789' * 100


@pytest.fixture(scope='module')
def mock_url_response(mock_response_data):
    """Function to add a `responses` mock URL with `mock_response_data` body."""
    def _mock_url_response(
            url: str, rsps: Union[responses.RequestsMock, None] = None):
        nonlocal mock_response_data
        if rsps is None:
            rsps = responses
        rsps.add(
            method=responses.GET,
            url=url,
            body=mock_response_data,
            headers={}
            )
    return _mock_url_response


@pytest.fixture
def creditsuisse21en_by_id_response():
    """Credit Suisse 2021 English AFR filing by `api_id`."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('creditsuisse21en_by_id'))
        yield rsps


@pytest.fixture
def creditsuisse21en_by_id_entity_response():
    """Credit Suisse 2021 English AFR filing by `api_id` and with Entity."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('creditsuisse21en_by_id_entity'))
        yield rsps


@pytest.fixture
def asml22en_response():
    """ASML Holding 2022 English AFR filing."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('asml22en'))
        yield rsps


@pytest.fixture
def asml22en_entities_response():
    """ASML Holding 2022 English AFR filing with entity."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('asml22en_entities'))
        yield rsps


@pytest.fixture
def asml22en_vmessages_response():
    """ASML Holding 2022 English AFR filing with validation messages."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('asml22en_vmessages'))
        yield rsps


@pytest.fixture
def assicurazioni21it_vmessages_response():
    """Assicurazioni Generali 2021 Italian AFR filing with validation messages."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('assicurazioni21it_vmessages'))
        yield rsps


@pytest.fixture
def tecnotree21fi_vmessages_response():
    """Tecnotree 2021 Finnish AFR filing with validation messages."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('tecnotree21fi_vmessages'))
        yield rsps


@pytest.fixture
def asml22en_ent_vmsg_response():
    """ASML Holding 2022 English AFR filing with entities and v-messages."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('asml22en_ent_vmsg'))
        yield rsps


@pytest.fixture
def filter_language_response():
    """Filter by language 'fi'."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_language'))
        yield rsps


@pytest.fixture
def filter_last_end_date_response():
    """Filter by last_end_date '2021-02-28'."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_last_end_date'))
        yield rsps


@pytest.fixture
def filter_last_end_date_lax_response():
    """Filter by last_end_date '2021-02-28'."""
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps._add_from_file(_get_path('filter_last_end_date'))
        yield rsps


@pytest.fixture
def filter_error_count_response():
    """Filter by error_count value 1."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_error_count'))
        yield rsps


@pytest.fixture
def filter_added_time_response():
    """Filter by added_time value '2021-09-23 00:00:00'."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_added_time'))
        yield rsps


@pytest.fixture
def filter_added_time_lax_response():
    """Filter by added_time value '2021-09-23 00:00:00'."""
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps._add_from_file(_get_path('filter_added_time'))
        yield rsps


@pytest.fixture
def filter_added_time_2_response():
    """Filter by added_time value '2023-05-09 13:27:02.676029'."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_added_time_2'))
        yield rsps


@pytest.fixture
def filter_added_time_2_lax_response():
    """Filter by added_time value '2023-05-09 13:27:02.676029'."""
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps._add_from_file(_get_path('filter_added_time_2'))
        yield rsps


@pytest.fixture
def filter_entity_api_id_response():
    """Return error when filtering with `entity_api_id`."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_entity_api_id'))
        yield rsps


@pytest.fixture
def filter_entity_api_id_lax_response():
    """Return error when filtering with `entity_api_id`."""
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps._add_from_file(_get_path('filter_entity_api_id'))
        yield rsps


@pytest.fixture
def filter_package_url_response():
    """Filter by package_url of Kone 2022 filing."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_package_url'))
        yield rsps


@pytest.fixture
def filter_package_sha256_response():
    """Filter by package_sha256 of Kone 2022 filing."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filter_package_sha256'))
        yield rsps


@pytest.fixture
def finnish_jan22_response():
    """Finnish AFR filings with reporting period ending in Jan 2022."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('finnish_jan22'))
        yield rsps


@pytest.fixture
def oldest3_fi_response():
    """Oldest 3 AFR filings reported in Finland."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('oldest3_fi'))
        yield rsps


@pytest.fixture
def sort_two_fields_response():
    """
    Sort Finnish filings by `last_end_date` and `added_time`.

    .. warning::

        Volatile with ``mock_upgrade.py`` run. See test
        ``test_query_sort::test_sort_two_fields``.
    """
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('sort_two_fields'))
        yield rsps


@pytest.fixture
def multipage_response():
    """Get 3 pages (2pc) of oldest Swedish filings."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('multipage'))
        yield rsps


@pytest.fixture
def multipage_lax_response():
    """Get 3 pages (2pc) of oldest Swedish filings."""
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        rsps._add_from_file(_get_path('multipage'))
        yield rsps


@pytest.fixture
def api_id_multifilter_response():
    """Get 4 Shell filings for 2021 and 2022."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('api_id_multifilter'))
        yield rsps


@pytest.fixture
def country_multifilter_response():
    """Get three filings for the first country `FI`."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('country_multifilter'))
        yield rsps


@pytest.fixture
def filing_index_multifilter_response():
    """Get three filings for the first country `FI`."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('filing_index_multifilter'))
        yield rsps


@pytest.fixture
def reporting_date_multifilter_response():
    """Return an error for filtering with `reporting_date`."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('reporting_date_multifilter'))
        yield rsps


@pytest.fixture
def inconsistency_count_multifilter_response():
    """Return an error for filtering with `inconsistency_count`."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('inconsistency_count_multifilter'))
        yield rsps


@pytest.fixture
def processed_time_multifilter_response():
    """Get two filings filtered with `processed_time`."""
    with responses.RequestsMock() as rsps:
        rsps._add_from_file(_get_path('processed_time_multifilter'))
        yield rsps
